### PR TITLE
fix: Update dependency @google-cloud/logging from 9.0.0 to 9.6.9

### LINKED ISSUE #666: Update dependency @google-cloud/logging from 9.0.0 to 9.6.9
1) Is this a client library issue or a product issue?
This is the client library issue for google-logging
 "GoogleError: Total timeout of API google.logging.v2.LoggingServiceV2 exceeded 60000 milliseconds before any response was received"
https://github.com/googleapis/nodejs-logging/issues/1185

2) Did someone already solve this?
Error has been fixed to @google-cloud/logging version 9.6.9 
https://github.com/googleapis/nodejs-logging/pull/1225

### PR DESCRIPTION
**Pull request by losalex**
This is a fix to expose a default callback from `Options` used by `LoggingWinston` so it would be propagated to `Log` constructor from `@google-cloud/logging` npm package. Also, update `@google-cloud/logging` dependency to 9.6.9.

Fixes #[666](https://github.com/googleapis/nodejs-logging-winston/issues/666) 🦕

### CODE REVIEW

**Review by arbrown — APPROVED** [review]

File: test/common.ts [hunk 1]
```diff
@@ -158,6 +158,20 @@ describe('logging-common', () => {
       assert.deepStrictEqual(fakeLogOptions_, {
         removeCircular: true,
         maxEntrySize: 250000,
+        defaultWriteDeleteCallback: undefined,
+      });
+    });
+
+    it('should set defualt callback', () => {
```
Comment (simonz130) [inline test/common.ts:165]: nit: typo - default

**Review by simonz130 — APPROVED** [review]

File: test/common.ts (hunk 1 above)
Comment (losalex) [reply test/common.ts:165]: Ah, right

File: .readme-partials.yaml [hunk 2]
```diff
@@ -100,6 +100,29 @@ body: |-
 
     You may also want to see the [@google-cloud/error-reporting](https://github.com/googleapis/nodejs-error-reporting) module which provides direct access to the Error Reporting API.
 
+    ### Error handling with a default callback
+
+    The `LoggingWinston` class creates an instance of `LoggingCommon` class which uses `Log` class from `@google-cloud/logging` package to write log entries.
```
Comment (arbrown) [inline .readme-partials.yaml:105]:
```suggestion
    The `LoggingWinston` class creates an instance of `LoggingCommon`  which uses the `Log` class from `@google-cloud/logging` package to write log entries. 
```

File: .readme-partials.yaml [hunk 3]
```diff
@@ -100,6 +100,29 @@ body: |-
 
     You may also want to see the [@google-cloud/error-reporting](https://github.com/googleapis/nodejs-error-reporting) module which provides direct access to the Error Reporting API.
 
+    ### Error handling with a default callback
+
+    The `LoggingWinston` class creates an instance of `LoggingCommon` class which uses `Log` class from `@google-cloud/logging` package to write log entries. 
+    The `Log` class writes logs asynchronously and there are cases when log entries cannot be written and the error is 
+    thrown - if error is not handled properly, it could crash the application. One possible way to handle the error is to provide a default callback
```
Comment (arbrown) [inline .readme-partials.yaml:107]:
```suggestion
    thrown - if the error is not handled properly, it could crash the application. One possible way to handle the error is to provide a default callback
```

File: .readme-partials.yaml [hunk 4]
```diff
@@ -100,6 +100,29 @@ body: |-
...
+    to `LoggingWinston` constructor which will be used to initialize `Log` object with that callback like in example below:
```
Comment (arbrown) [inline .readme-partials.yaml:108]:
```suggestion
    to the `LoggingWinston` constructor which will be used to initialize a `Log` object with that callback like in the example below:
```

**Review by arbrown — APPROVED** [review]
